### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by mujehoxe** [phronmophobic/grease#3]
Is there support for android, or is there an equivalent project for the platform?

**Comment by phronmophobic** [comment]
There's not currently support for android, but you should be able to follow the same process I used to get it working iOS. Are you on the clojurians slack? I wrote up some notes that might be helpful, https://clojurians.slack.com/archives/C0260KHN0Q0/p1638032063006400

**Comment by mujehoxe** [comment]
Okay will do, thanks
